apiVersion: v1
kind: Service
metadata:
  name: kafka-srv
spec:
  type: ClusterIP
  selector:
    app: kafka
  ports:
    - name: internal
      port: 9092
      targetPort: 9092
    - name: controller
      port: 9093
      targetPort: 9093
    - name: external
      port: 9094
      targetPort: 9094
      # nodePort: 30094  # dışarıya açık port
