apiVersion: v1
kind: Service
metadata:
  name: auth-srv  
spec:
  type: ClusterIP    
  selector:
    app: auth
  ports:
  - name: auth
    protocol: TCP
    port: 4003          
    targetPort: 4003   