apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl 
  labels:
    app: auth 
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: auth 

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1  
      maxSurge: 1        

  template:  
    metadata:
      labels:
        app: auth  
    spec:
      containers:
      - name: auth  
        image: auth  
        imagePullPolicy: Never
        ports:
        - name: auth
          containerPort: 4003  
        livenessProbe:
          httpGet:
            path: /health  
            port: 4003     
          initialDelaySeconds: 30  
          periodSeconds: 10         
        readinessProbe:
          httpGet:
            path: /ready  
            port: 4003
          initialDelaySeconds: 5  
          periodSeconds: 5

        resources:  
          requests:
            cpu: "250m"  
            memory: "256Mi"  
          limits:
            cpu: "1000m"
            memory: "1024Mi"
            
        envFrom:
          - configMapRef:
              name: global-config
              
        env:  
        - name: JWT_CLIENT_PRIVATE_TOKEN_BASE64
          valueFrom:
            secretKeyRef:
              name: easyshop-secret
              key: JWT_CLIENT_PRIVATE_TOKEN_BASE64
        - name: ELASTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: easyshop-secret
              key: ELASTIC_PASSWORD
        - name: AUTH_POSTGRES_URL
          valueFrom:
            secretKeyRef:
              name: easyshop-secret
              key: AUTH_POSTGRES_URL