apiVersion: v1
kind: Service
metadata:
  name: postgres-auth-srv  
spec:
  type: ClusterIP     
  selector:
    app: postgres-auth
  ports:
  - name: postgres-auth
    protocol: TCP
    port: 5432          
    targetPort: 5432  