apiVersion: v1
kind: Service
metadata:
  name: api-gateway-srv  
spec:
  type: ClusterIP     
  selector:
    app: api-gateway
  ports:
  - name: api-gateway
    protocol: TCP
    port: 4001          
    targetPort: 4001  