apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-api-gateway-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
          #Cache için kullandığım için Kalıcılık yok, volume yok
          args: ["--save", "", "--appendonly", "no"]