apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-user-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-user
  template:
    metadata:
      labels:
        app: postgres-user
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432

          env:
            - name: POSTGRES_USER
              value: "user_service"
            - name: POSTGRES_DB
              value: "user_db"

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: easyshop-secret
                  key: USER_POSTGRES_PASSWORD



          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-user-pvc
