apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-order-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-order
  template:
    metadata:
      labels:
        app: postgres-order
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432

          env:
            - name: POSTGRES_USER
              value: "order_service"
            - name: POSTGRES_DB
              value: "order_db"

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: easyshop-secret
                  key: ORDER_POSTGRES_PASSWORD

          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-order-pvc
