apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: product-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: product-depl
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60  # Yüzde 60 CPU kullanımına göre ölçeklenir

    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70 # Yüzde 70 RAM kullanımına göre ölçeklenir
