apiVersion: v1
kind: Service
metadata:
  name: product-srv  
spec:
  type: ClusterIP    
  selector:
    app: product
  ports:
  - name: product
    protocol: TCP
    port: 4005       
    targetPort: 4005