apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-depl 
  labels:
    app: product 
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: product 

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1  
      maxSurge: 1        

  template:  
    metadata:
      labels:
        app: product  
    spec:
      containers:
      - name: product  
        image: product  
        imagePullPolicy: Never
        ports:
        - name: product
          containerPort: 4005
        livenessProbe:
          httpGet:
            path: /health  
            port: 4005
          initialDelaySeconds: 30  
          periodSeconds: 10         
        readinessProbe:
          httpGet:
            path: /ready  
            port: 4005
          initialDelaySeconds: 5  
          periodSeconds: 5

        resources:  
          requests:
            cpu: "250m"  
            memory: "256Mi"  
          limits:
            cpu: "1000m"
            memory: "1024Mi"
            
        envFrom:
          - configMapRef:
              name: global-config
              
        env:  
        - name: ELASTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: easyshop-secret
              key: ELASTIC_PASSWORD
        - name: PRODUCT_POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: easyshop-secret
              key: PRODUCT_POSTGRES_PASSWORD
        - name: STRIPE_TEST_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: easyshop-secret
              key: STRIPE_TEST_SECRET_KEY