apiVersion: v1
kind: Service
metadata:
  name: kibana-srv
spec:
  type: NodePort
  selector:
    app: kibana
  ports:
    - name: web
      port: 5601
      targetPort: 5601
      nodePort: 30060  # dışarıya açık port
