apiVersion: v1
kind: Service
metadata:
  name: review-srv  
spec:
  type: ClusterIP    
  selector:
    app: review
  ports:
  - name: review
    protocol: TCP
    port: 4008      
    targetPort: 4008