apiVersion: v1
kind: Service
metadata:
  name: search-srv  
spec:
  type: ClusterIP    
  selector:
    app: search
  ports:
  - name: search
    protocol: TCP
    port: 4006       
    targetPort: 4006